# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: Build and Test

# This determines when this workflow is run
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '43 1 * * *'

jobs:
  industrial_ci:
    strategy:
      fail-fast: false
      matrix:
        env:
          - ROS_DISTRO: jazzy
          - ROS_DISTRO: humble
          - ROS_DISTRO: rolling

    env:
      CCACHE_DIR: /github/home/.ccache
      CXXFLAGS: "-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls"
      ROS_REPO: main

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # This step will fetch/store the directory used by ccache before/after the ci run
      - uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-{{ matrix.env.ROS_DISTRO }}-{{ matrix.env.ROS_REPO }}
      # Run industrial_ci
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
